from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import psycopg
from psycopg.rows import dict_row


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_SQLITE_PATH = BASE_DIR / "data" / "support_tracker.db"

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS support_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_date TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    requester_name TEXT NOT NULL DEFAULT '',
    service_id INTEGER NOT NULL REFERENCES services(id),
    support_content TEXT NOT NULL,
    channel TEXT NOT NULL,
    supporter_name TEXT NOT NULL,
    status TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_support_date ON support_records(support_date);
CREATE INDEX IF NOT EXISTS idx_support_service ON support_records(service_id);
CREATE INDEX IF NOT EXISTS idx_support_status ON support_records(status);
CREATE INDEX IF NOT EXISTS idx_support_supporter ON support_records(supporter_name);
CREATE INDEX IF NOT EXISTS idx_support_requester ON support_records(requester_name);
"""

LEGACY_CHANNEL_MAP = {
    "Ultra khach": "Group ĐTP-AM-Hỗ trợ",
    "Ultra khách": "Group ĐTP-AM-Hỗ trợ",
    "Zalo": "Nhắn tin riêng",
    "Truc tiep": "Khác",
    "Trực tiếp": "Khác",
    "Cong dong Hoa don": "Cộng đồng hóa đơn",
    "Cộng đồng Hóa đơn": "Cộng đồng hóa đơn",
}


def normalize_database_url(value: str) -> str:
    if value.startswith("postgres://"):
        return f"postgresql://{value[len('postgres://'):]}"
    return value


def normalize_text(value: Any) -> str:
    return " ".join(str(value or "").strip().split())


def iso_now() -> str:
    return datetime.now().replace(microsecond=0).isoformat()


def canonical_channel_name(value: Any) -> str:
    raw = normalize_text(value)
    if not raw:
        return ""
    return LEGACY_CHANNEL_MAP.get(raw, raw)


def execute_script(db: Any, script: str) -> None:
    for statement in script.split(";"):
        cleaned = statement.strip()
        if cleaned:
            db.execute(cleaned)


def ensure_postgres_schema(db: Any) -> None:
    execute_script(db, POSTGRES_SCHEMA_SQL)
    db.execute(
        """
        ALTER TABLE support_records
        ADD COLUMN IF NOT EXISTS requester_name TEXT NOT NULL DEFAULT ''
        """
    )


def sqlite_table_columns(sqlite_db: sqlite3.Connection, table_name: str) -> set[str]:
    rows = sqlite_db.execute(f"PRAGMA table_info({table_name})").fetchall()
    return {row["name"] for row in rows}


def load_sqlite_rows(sqlite_path: Path) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    if not sqlite_path.exists():
        raise FileNotFoundError(f"Khong tim thay file SQLite: {sqlite_path}")

    sqlite_db = sqlite3.connect(sqlite_path)
    sqlite_db.row_factory = sqlite3.Row
    try:
        support_record_columns = sqlite_table_columns(sqlite_db, "support_records")
        requester_select = (
            "COALESCE(requester_name, '') AS requester_name"
            if "requester_name" in support_record_columns
            else "'' AS requester_name"
        )
        services = [
            dict(row)
            for row in sqlite_db.execute(
                """
                SELECT id, name, description, is_active, created_at, updated_at
                FROM services
                ORDER BY id
                """
            ).fetchall()
        ]
        entries = [
            dict(row)
            for row in sqlite_db.execute(
                f"""
                SELECT
                    support_records.id AS id,
                    support_records.support_date,
                    support_records.customer_name,
                    {requester_select},
                    support_records.service_id,
                    services.name AS service_name,
                    support_records.support_content,
                    support_records.channel,
                    support_records.supporter_name,
                    support_records.status,
                    support_records.notes,
                    support_records.created_at,
                    support_records.updated_at
                FROM support_records
                LEFT JOIN services ON services.id = support_records.service_id
                ORDER BY support_records.id
                """
            ).fetchall()
        ]
    finally:
        sqlite_db.close()

    for entry in entries:
        entry["channel"] = canonical_channel_name(entry.get("channel"))

    return services, entries


def fetch_postgres_counts(db: Any) -> dict[str, int]:
    service_total = db.execute("SELECT COUNT(*) AS total FROM services").fetchone()["total"]
    entry_total = db.execute("SELECT COUNT(*) AS total FROM support_records").fetchone()["total"]
    return {
        "services": service_total,
        "support_records": entry_total,
    }


def clear_postgres_data(db: Any) -> None:
    db.execute("DELETE FROM support_records")
    db.execute("DELETE FROM services")


def get_or_create_fallback_service(
    db: Any,
    service_mapping: dict[int, int],
    entry: dict[str, Any],
) -> int:
    source_service_id = int(entry["service_id"])
    fallback_name = normalize_text(entry.get("service_name")) or f"Dich vu cu ID {source_service_id}"
    existing = db.execute(
        """
        SELECT id
        FROM services
        WHERE name = %s
        """,
        (fallback_name,),
    ).fetchone()
    if existing:
        mapped_service_id = existing["id"]
        service_mapping[source_service_id] = mapped_service_id
        return mapped_service_id

    timestamp = entry.get("updated_at") or entry.get("created_at") or iso_now()
    description = (
        f"Tu dong tao khi migrate vi support_records tham chieu service_id cu {source_service_id} "
        "nhung ban ghi dich vu goc khong con trong SQLite."
    )
    cursor = db.execute(
        """
        INSERT INTO services (name, description, is_active, created_at, updated_at)
        VALUES (%s, %s, %s, %s, %s)
        RETURNING id
        """,
        (
            fallback_name,
            description,
            0,
            timestamp,
            timestamp,
        ),
    )
    mapped_service_id = cursor.fetchone()["id"]
    service_mapping[source_service_id] = mapped_service_id
    return mapped_service_id


def sync_services(
    db: Any,
    services: list[dict[str, Any]],
) -> tuple[dict[int, int], dict[str, int]]:
    mapping: dict[int, int] = {}
    stats = {
        "inserted": 0,
        "updated": 0,
    }

    target_rows = db.execute(
        """
        SELECT id, name
        FROM services
        """
    ).fetchall()
    target_by_id = {row["id"]: dict(row) for row in target_rows}
    target_by_name = {row["name"]: dict(row) for row in target_rows}

    for service in services:
        source_id = int(service["id"])
        same_id = target_by_id.get(source_id)
        same_name = target_by_name.get(service["name"])

        if same_id:
            db.execute(
                """
                UPDATE services
                SET
                    name = %s,
                    description = %s,
                    is_active = %s,
                    created_at = %s,
                    updated_at = %s
                WHERE id = %s
                """,
                (
                    service["name"],
                    service["description"],
                    int(service["is_active"]),
                    service["created_at"],
                    service["updated_at"],
                    same_id["id"],
                ),
            )
            mapping[source_id] = same_id["id"]
            stats["updated"] += 1
            continue

        if same_name:
            db.execute(
                """
                UPDATE services
                SET
                    description = %s,
                    is_active = %s,
                    created_at = %s,
                    updated_at = %s
                WHERE id = %s
                """,
                (
                    service["description"],
                    int(service["is_active"]),
                    service["created_at"],
                    service["updated_at"],
                    same_name["id"],
                ),
            )
            mapping[source_id] = same_name["id"]
            stats["updated"] += 1
            continue

        db.execute(
            """
            INSERT INTO services (id, name, description, is_active, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s)
            """,
            (
                source_id,
                service["name"],
                service["description"],
                int(service["is_active"]),
                service["created_at"],
                service["updated_at"],
            ),
        )
        mapping[source_id] = source_id
        stats["inserted"] += 1

    return mapping, stats


def sync_support_records(
    db: Any,
    entries: list[dict[str, Any]],
    service_mapping: dict[int, int],
) -> dict[str, int]:
    stats = {
        "inserted": 0,
        "updated": 0,
        "fallback_services": 0,
    }

    existing_ids = {
        row["id"]
        for row in db.execute("SELECT id FROM support_records").fetchall()
    }

    for entry in entries:
        source_service_id = int(entry["service_id"])
        mapped_service_id = service_mapping.get(source_service_id)
        if mapped_service_id is None:
            mapped_service_id = get_or_create_fallback_service(db, service_mapping, entry)
            stats["fallback_services"] += 1
        payload = (
            entry["support_date"],
            entry["customer_name"],
            normalize_text(entry.get("requester_name", "")),
            mapped_service_id,
            entry["support_content"],
            canonical_channel_name(entry["channel"]),
            entry["supporter_name"],
            entry["status"],
            entry["notes"],
            entry["created_at"],
            entry["updated_at"],
            int(entry["id"]),
        )

        if int(entry["id"]) in existing_ids:
            db.execute(
                """
                UPDATE support_records
                SET
                    support_date = %s,
                    customer_name = %s,
                    requester_name = %s,
                    service_id = %s,
                    support_content = %s,
                    channel = %s,
                    supporter_name = %s,
                    status = %s,
                    notes = %s,
                    created_at = %s,
                    updated_at = %s
                WHERE id = %s
                """,
                payload,
            )
            stats["updated"] += 1
            continue

        db.execute(
            """
            INSERT INTO support_records (
                support_date,
                customer_name,
                requester_name,
                service_id,
                support_content,
                channel,
                supporter_name,
                status,
                notes,
                created_at,
                updated_at,
                id
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            payload,
        )
        stats["inserted"] += 1

    return stats


def reset_identity_sequence(db: Any, table_name: str) -> None:
    max_id = db.execute(f"SELECT COALESCE(MAX(id), 0) AS max_id FROM {table_name}").fetchone()["max_id"]
    if max_id > 0:
        db.execute(
            "SELECT setval(pg_get_serial_sequence(%s, 'id'), %s, true)",
            (table_name, max_id),
        )
        return

    db.execute(
        "SELECT setval(pg_get_serial_sequence(%s, 'id'), 1, false)",
        (table_name,),
    )


def require_database_url(cli_value: str | None) -> str:
    database_url = normalize_database_url((cli_value or os.getenv("DATABASE_URL", "")).strip())
    if not database_url:
        raise RuntimeError(
            "Chua co DATABASE_URL. Hay dung --database-url hoac set bien moi truong DATABASE_URL."
        )
    return database_url


def confirm_clear_target() -> None:
    answer = input(
        "Ban sap xoa toan bo du lieu hien co trong PostgreSQL truoc khi import. "
        "Nhap YES de tiep tuc: "
    ).strip()
    if answer != "YES":
        raise RuntimeError("Da huy thao tac xoa du lieu dich.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Chuyen du lieu tu SQLite local len PostgreSQL."
    )
    parser.add_argument(
        "--sqlite-path",
        default=str(DEFAULT_SQLITE_PATH),
        help="Duong dan toi file SQLite local. Mac dinh: data/support_tracker.db",
    )
    parser.add_argument(
        "--database-url",
        default="",
        help="URL PostgreSQL dich. Co the bo qua neu da set DATABASE_URL.",
    )
    parser.add_argument(
        "--clear-target",
        action="store_true",
        help="Xoa du lieu hien co tren PostgreSQL truoc khi import.",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Bo qua hoi xac nhan khi dung --clear-target.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sqlite_path = Path(args.sqlite_path).expanduser().resolve()
    database_url = require_database_url(args.database_url)

    print(f"[1/5] Doc du lieu SQLite tu: {sqlite_path}")
    services, entries = load_sqlite_rows(sqlite_path)
    print(f"       Tim thay {len(services)} dich vu va {len(entries)} luot ho tro.")

    print("[2/5] Ket noi PostgreSQL")
    postgres_db = psycopg.connect(database_url, row_factory=dict_row)

    try:
        print("[3/5] Tao schema neu chua co")
        ensure_postgres_schema(postgres_db)

        before_counts = fetch_postgres_counts(postgres_db)
        print(
            "       PostgreSQL hien co "
            f"{before_counts['services']} dich vu, {before_counts['support_records']} luot ho tro."
        )

        if args.clear_target:
            if not args.yes:
                confirm_clear_target()
            clear_postgres_data(postgres_db)
            print("       Da xoa du lieu cu tren PostgreSQL.")

        print("[4/5] Dong bo dich vu va luot ho tro")
        service_mapping, service_stats = sync_services(postgres_db, services)
        entry_stats = sync_support_records(postgres_db, entries, service_mapping)

        reset_identity_sequence(postgres_db, "services")
        reset_identity_sequence(postgres_db, "support_records")
        postgres_db.commit()

        after_counts = fetch_postgres_counts(postgres_db)
        print("[5/5] Hoan tat")
        print(
            "       Dich vu: "
            f"{service_stats['inserted']} them moi, {service_stats['updated']} cap nhat."
        )
        print(
            "       Luot ho tro: "
            f"{entry_stats['inserted']} them moi, {entry_stats['updated']} cap nhat."
        )
        if entry_stats["fallback_services"]:
            print(
                "       Canh bao: da tu dong tao "
                f"{entry_stats['fallback_services']} dich vu bu cho cac service_id cu khong con trong SQLite."
            )
        print(
            "       Tong sau cung tren PostgreSQL: "
            f"{after_counts['services']} dich vu, {after_counts['support_records']} luot ho tro."
        )
        print("")
        print("Luu y:")
        print("- Neu day la database Render dung cho app production, app tren Render nen dung Internal Database URL.")
        print("- Script nay chay tu may cua ban nen thuong phai dung External Database URL cua Render.")
        return 0
    except Exception:
        postgres_db.rollback()
        raise
    finally:
        postgres_db.close()


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"Loi: {exc}", file=sys.stderr)
        raise SystemExit(1)
